name : "Testeo de la aplicacion"

on:
    push:
      branches:
         - release
    pull_request:
      branches:
         - release 


jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
        - name: Revisar el codigo y pasarlo a ubuntu
          uses: actions/checkout@v3

        - name: Prepara e instala PHP en mi ambiente
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
            extensions: mbstring, pdo, bcmath
            ini-values: post_max_size=256M, upload_max_filesize=256M
            coverage: none

        - name: Saludar
          run: php -r "echo 'hola a todos, es un placer saludarlos';"   

